### ISSUE TITLE
Units get stuck in "Waiting for peers" with more number of units

### ISSUE THREAD

**Issue by nobuto-m** [openstack-charmers/magpie-layer#21]
The issue reported some time ago is still reproducible with the latest revision and the latest stable Juju.
https://github.com/andrewdmcleod/magpie-layer/issues/10

juju version: 2.8.6
charm: cs:~openstack-charmers/magpie-0

The charm takes 11 minutes with 14 units until the model settles down which is okay. However with 28 units, it takes 27 minutes and most of the units are stuck in "Waiting for peers..." most of the time. We see this trend with 50 or 100 physical hosts in the field more than an hour taking easily.

$ juju deploy ./magpie_14units.yaml; time juju-wait -w
[magpie_14units.yaml.txt](https://github.com/openstack-charmers/magpie-layer/files/5551512/magpie_14units.yaml.txt)
-> 11 minutes

$ juju deploy ./magpie_28units.yaml; time juju-wait -w
[magpie_28units.yaml.txt](https://github.com/openstack-charmers/magpie-layer/files/5551515/magpie_28units.yaml.txt)
-> 27 minutes

Also, we usually have multiple network spaces to test like 5 spaces. If I'm not mistaken, Juju doesn't run hooks from multiple applications at the same time on a single unit so the whole test with 28 units with 5 spaces would take multiple hours easily.
https://github.com/openstack-charmers/magpie-layer/blob/master/README.md#network-spaces

At this point, we usually split 100 physical hosts into multiple models to mitigate the impact of this issue. However, it's not ideal because we would like to test cross-rack connectivity including jumbo frames at once.

**Comment by nobuto-m** [comment]
juju-crashdump with 28 units.
[juju-crashdump-911d8492-d51b-4ff5-ab28-d290daa356ca.tar.gz](https://github.com/openstack-charmers/magpie-layer/files/5551641/juju-crashdump-911d8492-d51b-4ff5-ab28-d290daa356ca.tar.gz)

**Comment by lourot** [comment]
Moved to new bugtracker: https://bugs.launchpad.net/charm-magpie/+bug/1908520
